version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=n11bootcamp-h4
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=123qwe
    ports:
      - '5432:5432'